In [23]:
import urllib.request

url = 'https://ckan.pf-sapporo.jp/api/action/datastore_search?resource_id=b83606f6-3aa2-4e0c-8a1a-509dd36be2ae'

with urllib.request.urlopen(url) as response:
    html = response.read()
    print(html)

b'{"help": "https://ckan.pf-sapporo.jp/api/3/action/help_show?name=datastore_search", "success": true, "result": {"resource_id": "b83606f6-3aa2-4e0c-8a1a-509dd36be2ae", "fields": [{"type": "int4", "id": "_id"}, {"type": "timestamp", "id": "\\u65e5\\u4ed8"}, {"type": "numeric", "id": "\\u5c0f\\u8a08"}], "records": [{"_id": 1, "\\u65e5\\u4ed8": "2020-02-14T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 2, "\\u65e5\\u4ed8": "2020-02-15T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 3, "\\u65e5\\u4ed8": "2020-02-16T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 4, "\\u65e5\\u4ed8": "2020-02-17T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 5, "\\u65e5\\u4ed8": "2020-02-18T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 6, "\\u65e5\\u4ed8": "2020-02-19T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 7, "\\u65e5\\u4ed8": "2020-02-20T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 8, "\\u65e5\\u4ed8": "2020-02-21T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 9, "\\u65e5\\u4ed8": "2020-02-22T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 10, "\\u65e5\\u4ed8": "2020-02-23T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 11, "\\u65e5\\u4ed8": "2020-02-24T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 12, "\\u65e5\\u4ed8": "2020-02-25T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 13, "\\u65e5\\u4ed8": "2020-02-26T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 14, "\\u65e5\\u4ed8": "2020-02-27T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 15, "\\u65e5\\u4ed8": "2020-02-28T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 16, "\\u65e5\\u4ed8": "2020-02-29T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 17, "\\u65e5\\u4ed8": "2020-03-01T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 18, "\\u65e5\\u4ed8": "2020-03-02T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 19, "\\u65e5\\u4ed8": "2020-03-03T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 20, "\\u65e5\\u4ed8": "2020-03-04T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 21, "\\u65e5\\u4ed8": "2020-03-05T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 22, "\\u65e5\\u4ed8": "2020-03-06T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 23, "\\u65e5\\u4ed8": "2020-03-07T08:00:00", "\\u5c0f\\u8a08": "6"}, {"_id": 24, "\\u65e5\\u4ed8": "2020-03-08T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 25, "\\u65e5\\u4ed8": "2020-03-09T08:00:00", "\\u5c0f\\u8a08": "5"}, {"_id": 26, "\\u65e5\\u4ed8": "2020-03-10T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 27, "\\u65e5\\u4ed8": "2020-03-11T08:00:00", "\\u5c0f\\u8a08": "4"}, {"_id": 28, "\\u65e5\\u4ed8": "2020-03-12T08:00:00", "\\u5c0f\\u8a08": "9"}, {"_id": 29, "\\u65e5\\u4ed8": "2020-03-13T08:00:00", "\\u5c0f\\u8a08": "6"}, {"_id": 30, "\\u65e5\\u4ed8": "2020-03-14T08:00:00", "\\u5c0f\\u8a08": "7"}, {"_id": 31, "\\u65e5\\u4ed8": "2020-03-15T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 32, "\\u65e5\\u4ed8": "2020-03-16T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 33, "\\u65e5\\u4ed8": "2020-03-17T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 34, "\\u65e5\\u4ed8": "2020-03-18T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 35, "\\u65e5\\u4ed8": "2020-03-19T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 36, "\\u65e5\\u4ed8": "2020-03-20T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 37, "\\u65e5\\u4ed8": "2020-03-21T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 38, "\\u65e5\\u4ed8": "2020-03-22T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 39, "\\u65e5\\u4ed8": "2020-03-23T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 40, "\\u65e5\\u4ed8": "2020-03-24T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 41, "\\u65e5\\u4ed8": "2020-03-25T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 42, "\\u65e5\\u4ed8": "2020-03-26T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 43, "\\u65e5\\u4ed8": "2020-03-27T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 44, "\\u65e5\\u4ed8": "2020-03-28T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 45, "\\u65e5\\u4ed8": "2020-03-29T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 46, "\\u65e5\\u4ed8": "2020-03-30T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 47, "\\u65e5\\u4ed8": "2020-03-31T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 48, "\\u65e5\\u4ed8": "2020-04-01T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 49, "\\u65e5\\u4ed8": "2020-04-02T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 50, "\\u65e5\\u4ed8": "2020-04-03T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 51, "\\u65e5\\u4ed8": "2020-04-04T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 52, "\\u65e5\\u4ed8": "2020-04-05T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 53, "\\u65e5\\u4ed8": "2020-04-06T08:00:00", "\\u5c0f\\u8a08": "0"}, {"_id": 54, "\\u65e5\\u4ed8": "2020-04-07T08:00:00", "\\u5c0f\\u8a08": "4"}, {"_id": 55, "\\u65e5\\u4ed8": "2020-04-08T08:00:00", "\\u5c0f\\u8a08": "4"}, {"_id": 56, "\\u65e5\\u4ed8": "2020-04-09T08:00:00", "\\u5c0f\\u8a08": "8"}, {"_id": 57, "\\u65e5\\u4ed8": "2020-04-10T08:00:00", "\\u5c0f\\u8a08": "8"}, {"_id": 58, "\\u65e5\\u4ed8": "2020-04-11T08:00:00", "\\u5c0f\\u8a08": "12"}, {"_id": 59, "\\u65e5\\u4ed8": "2020-04-12T08:00:00", "\\u5c0f\\u8a08": "10"}, {"_id": 60, "\\u65e5\\u4ed8": "2020-04-13T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 61, "\\u65e5\\u4ed8": "2020-04-14T08:00:00", "\\u5c0f\\u8a08": "10"}, {"_id": 62, "\\u65e5\\u4ed8": "2020-04-15T08:00:00", "\\u5c0f\\u8a08": "16"}, {"_id": 63, "\\u65e5\\u4ed8": "2020-04-16T08:00:00", "\\u5c0f\\u8a08": "10"}, {"_id": 64, "\\u65e5\\u4ed8": "2020-04-17T08:00:00", "\\u5c0f\\u8a08": "20"}, {"_id": 65, "\\u65e5\\u4ed8": "2020-04-18T08:00:00", "\\u5c0f\\u8a08": "23"}, {"_id": 66, "\\u65e5\\u4ed8": "2020-04-19T08:00:00", "\\u5c0f\\u8a08": "12"}, {"_id": 67, "\\u65e5\\u4ed8": "2020-04-20T08:00:00", "\\u5c0f\\u8a08": "8"}, {"_id": 68, "\\u65e5\\u4ed8": "2020-04-21T08:00:00", "\\u5c0f\\u8a08": "17"}, {"_id": 69, "\\u65e5\\u4ed8": "2020-04-22T08:00:00", "\\u5c0f\\u8a08": "13"}, {"_id": 70, "\\u65e5\\u4ed8": "2020-04-23T08:00:00", "\\u5c0f\\u8a08": "18"}, {"_id": 71, "\\u65e5\\u4ed8": "2020-04-24T08:00:00", "\\u5c0f\\u8a08": "14"}, {"_id": 72, "\\u65e5\\u4ed8": "2020-04-25T08:00:00", "\\u5c0f\\u8a08": "26"}, {"_id": 73, "\\u65e5\\u4ed8": "2020-04-26T08:00:00", "\\u5c0f\\u8a08": "11"}, {"_id": 74, "\\u65e5\\u4ed8": "2020-04-27T08:00:00", "\\u5c0f\\u8a08": "26"}, {"_id": 75, "\\u65e5\\u4ed8": "2020-04-28T08:00:00", "\\u5c0f\\u8a08": "25"}, {"_id": 76, "\\u65e5\\u4ed8": "2020-04-29T08:00:00", "\\u5c0f\\u8a08": "26"}, {"_id": 77, "\\u65e5\\u4ed8": "2020-04-30T08:00:00", "\\u5c0f\\u8a08": "27"}, {"_id": 78, "\\u65e5\\u4ed8": "2020-05-01T08:00:00", "\\u5c0f\\u8a08": "21"}, {"_id": 79, "\\u65e5\\u4ed8": "2020-05-02T08:00:00", "\\u5c0f\\u8a08": "25"}, {"_id": 80, "\\u65e5\\u4ed8": "2020-05-03T08:00:00", "\\u5c0f\\u8a08": "22"}, {"_id": 81, "\\u65e5\\u4ed8": "2020-05-04T08:00:00", "\\u5c0f\\u8a08": "29"}, {"_id": 82, "\\u65e5\\u4ed8": "2020-05-05T08:00:00", "\\u5c0f\\u8a08": "9"}, {"_id": 83, "\\u65e5\\u4ed8": "2020-05-06T08:00:00", "\\u5c0f\\u8a08": "16"}, {"_id": 84, "\\u65e5\\u4ed8": "2020-05-07T08:00:00", "\\u5c0f\\u8a08": "9"}, {"_id": 85, "\\u65e5\\u4ed8": "2020-05-08T08:00:00", "\\u5c0f\\u8a08": "4"}, {"_id": 86, "\\u65e5\\u4ed8": "2020-05-09T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 87, "\\u65e5\\u4ed8": "2020-05-10T08:00:00", "\\u5c0f\\u8a08": "9"}, {"_id": 88, "\\u65e5\\u4ed8": "2020-05-11T08:00:00", "\\u5c0f\\u8a08": "12"}, {"_id": 89, "\\u65e5\\u4ed8": "2020-05-12T08:00:00", "\\u5c0f\\u8a08": "10"}, {"_id": 90, "\\u65e5\\u4ed8": "2020-05-13T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 91, "\\u65e5\\u4ed8": "2020-05-14T08:00:00", "\\u5c0f\\u8a08": "6"}, {"_id": 92, "\\u65e5\\u4ed8": "2020-05-15T08:00:00", "\\u5c0f\\u8a08": "4"}, {"_id": 93, "\\u65e5\\u4ed8": "2020-05-16T08:00:00", "\\u5c0f\\u8a08": "5"}, {"_id": 94, "\\u65e5\\u4ed8": "2020-05-17T08:00:00", "\\u5c0f\\u8a08": "6"}, {"_id": 95, "\\u65e5\\u4ed8": "2020-05-18T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 96, "\\u65e5\\u4ed8": "2020-05-19T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 97, "\\u65e5\\u4ed8": "2020-05-20T08:00:00", "\\u5c0f\\u8a08": "1"}, {"_id": 98, "\\u65e5\\u4ed8": "2020-05-21T08:00:00", "\\u5c0f\\u8a08": "2"}, {"_id": 99, "\\u65e5\\u4ed8": "2020-05-22T08:00:00", "\\u5c0f\\u8a08": "3"}, {"_id": 100, "\\u65e5\\u4ed8": "2020-05-23T08:00:00", "\\u5c0f\\u8a08": "7"}], "_links": {"start": "/api/action/datastore_search?resource_id=b83606f6-3aa2-4e0c-8a1a-509dd36be2ae", "next": "/api/action/datastore_search?offset=100&resource_id=b83606f6-3aa2-4e0c-8a1a-509dd36be2ae"}, "total": 300}}'

In [56]:
import json
import urllib
import pandas as pd

url = 'https://ckan.pf-sapporo.jp/api/action/datastore_search?resource_id=b83606f6-3aa2-4e0c-8a1a-509dd36be2ae&limit=1000'

df = pd.DataFrame()
req = urllib.request.Request(url)

with urllib.request.urlopen(req) as res:
    body = json.load(res)
    df = pd.DataFrame(body['result']['records'])

df

     _id                   日付   小計
0      1  2020-02-14T08:00:00    1
1      2  2020-02-15T08:00:00    0
2      3  2020-02-16T08:00:00    0
3      4  2020-02-17T08:00:00    0
4      5  2020-02-18T08:00:00    1
..   ...                  ...  ...
295  296  2020-12-05T08:00:00  111
296  297  2020-12-06T08:00:00  133
297  298  2020-12-07T08:00:00   87
298  299  2020-12-08T08:00:00  112
299  300  2020-12-09T08:00:00   95

[300 rows x 3 columns]

In [27]:
body

{'help': 'https://ckan.pf-sapporo.jp/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'resource_id': 'b83606f6-3aa2-4e0c-8a1a-509dd36be2ae',
  'fields': [{'type': 'int4', 'id': '_id'},
   {'type': 'timestamp', 'id': '日付'},
   {'type': 'numeric', 'id': '小計'}],
  'records': [{'_id': 1, '日付': '2020-02-14T08:00:00', '小計': '1'},
   {'_id': 2, '日付': '2020-02-15T08:00:00', '小計': '0'},
   {'_id': 3, '日付': '2020-02-16T08:00:00', '小計': '0'},
   {'_id': 4, '日付': '2020-02-17T08:00:00', '小計': '0'},
   {'_id': 5, '日付': '2020-02-18T08:00:00', '小計': '1'},
   {'_id': 6, '日付': '2020-02-19T08:00:00', '小計': '1'},
   {'_id': 7, '日付': '2020-02-20T08:00:00', '小計': '0'},
   {'_id': 8, '日付': '2020-02-21T08:00:00', '小計': '0'},
   {'_id': 9, '日付': '2020-02-22T08:00:00', '小計': '1'},
   {'_id': 10, '日付': '2020-02-23T08:00:00', '小計': '0'}],
  '_links': {'start': '/api/action/datastore_search?limit=10&resource_id=b83606f6-3aa2-4e0c-8a1a-509dd36be2ae',
   'next': '/api/action/datastore_search?offset=10&limit=10&resource_id=b83606f6-3aa2-4e0c-8a1a-509dd36be2ae'},
  'limit': 10,
  'total': 300}}

In [31]:
body['result']['records']

[{'_id': 1, '日付': '2020-02-14T08:00:00', '小計': '1'},
 {'_id': 2, '日付': '2020-02-15T08:00:00', '小計': '0'},
 {'_id': 3, '日付': '2020-02-16T08:00:00', '小計': '0'},
 {'_id': 4, '日付': '2020-02-17T08:00:00', '小計': '0'},
 {'_id': 5, '日付': '2020-02-18T08:00:00', '小計': '1'},
 {'_id': 6, '日付': '2020-02-19T08:00:00', '小計': '1'},
 {'_id': 7, '日付': '2020-02-20T08:00:00', '小計': '0'},
 {'_id': 8, '日付': '2020-02-21T08:00:00', '小計': '0'},
 {'_id': 9, '日付': '2020-02-22T08:00:00', '小計': '1'},
 {'_id': 10, '日付': '2020-02-23T08:00:00', '小計': '0'}]

In [32]:
import pandas as pd
df = pd.DataFrame(body['result']['records'])

In [33]:
df

   _id                   日付 小計
0    1  2020-02-14T08:00:00  1
1    2  2020-02-15T08:00:00  0
2    3  2020-02-16T08:00:00  0
3    4  2020-02-17T08:00:00  0
4    5  2020-02-18T08:00:00  1
5    6  2020-02-19T08:00:00  1
6    7  2020-02-20T08:00:00  0
7    8  2020-02-21T08:00:00  0
8    9  2020-02-22T08:00:00  1
9   10  2020-02-23T08:00:00  0

In [58]:
import requests
import io
import pandas as pd

url = 'https://ckan.pf-sapporo.jp/dataset/c89f65e7-45a8-4ab2-b94d-494ae192c70f/resource/b83606f6-3aa2-4e0c-8a1a-509dd36be2ae/download/patientssummary.csv'

res = requests.get(url).content
df = pd.read_csv(io.StringIO(res.decode('utf-8')))

df

                           日付   小計
0    2020-02-14T08:00:00.000Z    1
1    2020-02-15T08:00:00.000Z    0
2    2020-02-16T08:00:00.000Z    0
3    2020-02-17T08:00:00.000Z    0
4    2020-02-18T08:00:00.000Z    1
..                        ...  ...
318  2020-12-28T08:00:00.000Z   61
319  2020-12-29T08:00:00.000Z   60
320  2020-12-30T08:00:00.000Z   60
321  2020-12-31T08:00:00.000Z  105
322  2021-01-01T08:00:00.000Z   64

[323 rows x 2 columns]